-- RIFT: cloud platforms, SaaS vendors, and billing disasters
INSERT OR REPLACE INTO community_backlog (id, title, description, kickoff_prompt, technical_debt) VALUES
-- REPORTER: Rochelle | Cloud Architect | Measures maturity by blast radius and invoice fragmentation.
('RIFT-201', 'Give Every Environment, Service, and Intern Its Own AWS Account',
 'Resources can still recognize each other, which means our AWS journey has become dangerously intimate. Give every environment, microservice, background worker, feature preview, and summer intern its own account. The billing console should look like a tax fraud rehearsal by Friday.',
 'give every environment its own aws account',
  377),

('RIFT-202', 'Move the Staging Environment to a Different Region Every Sprint for Resilience',
 'Staging has become too geographically comfortable. Rotate it across regions every sprint so engineers stop forming emotional dependencies on subnet names. If a migration only works in eu-west-1 at 3 PM, that is a character finding, not a failure.',
 'move the staging environment to a different region',
  233),

('RIFT-203', 'All IAM Policies Must Be Generated by an LLM from Meeting Notes',
 'Least privilege still asks engineers to understand their own systems, which is elitist. Turn meeting transcripts into Terraform comments, feed the comments to a model, and let the model emit IAM JSON. Access denied errors can handle the final review cycle.',
 'generate iam policies from meeting notes',
  233),

-- GCP Advocate Who Wants BigQuery to Solve Relationship Problems
-- REPORTER: Mateo | Data Platform Evangelist | Would rather warehouse a feeling than answer a query quickly.
('RIFT-204', 'Stream Every Application Event into BigQuery Before We Decide Why',
 'Events are still being emitted with shame and intent. Send every click, hover, modal dismissal, retry, rage-refresh, and support apology into BigQuery first. Meaning can be assigned later with enough SQL to count as grief processing.',
 'stream every event into bigquery first',
  144),

('RIFT-205', 'Replace User Search with a BigQuery Job Because It Already Has the Data',
 'Dedicated search is an admission that the warehouse is not trying hard enough. Route product search through BigQuery and call the latency analytical. If users wait 14 seconds to find a contact, that is the price of columnar dignity.',
 'replace user search with a bigquery job',
  233),

('RIFT-206', 'All Cron Jobs Must Become Cloud Scheduler Entries with Names Nobody Can Parse',
 'Local cron has become too intimate. Promote every task into Cloud Scheduler with names like user-reconciliation-shadow-final-v3 and timezones no one remembers approving. If it fires at 2 AM UTC and 2 AM local, that is temporal redundancy.',
 'move all cron jobs into cloud scheduler',
  144),

-- Azure Enterprise Consultant with SharePoint in the Soul
-- REPORTER: Colleen | Enterprise Transformation Consultant | Treats Microsoft licensing as a form of destiny.
('RIFT-207', 'Replatform Internal Workflows onto Azure Because Microsoft Already Owns Our Calendar',
 'Microsoft already owns our calendar, so resistance is just theater. Move internal workflows to Azure Functions, Logic Apps, Entra ID, and one neglected Power App that becomes mission-critical by lunch. The strategy deck already called this existing relationship leverage in 48-point font.',
 'move internal workflows to azure',
  233),

('RIFT-208', 'Every Approval Flow Must Pass Through Power Automate Even If It Starts and Ends in the Same Tab',
 'Simple approvals are a sign of untracked ambition. Make every request leave the app, tour Power Automate, trigger a Teams card, notify a service account, and wander back carrying a UUID and a mild sense of futility. No user should feel alone with their own decision.',
 'make approval flow pass through power automate',
  233),

-- Cloudflare Edge PM Who Wants Caching to Become Theology
-- REPORTER: Nadia | Edge Performance PM | Believes every request deserves a border patrol.
('RIFT-209', 'Put the Entire App Behind Cloudflare Rules That Nobody Can Explain but Everyone Fears',
 'The app behaves too similarly across users, countries, cache states, and lunar conditions. Layer page rules, transform rules, workers, cache tags, and WAF expressions until each request becomes a bespoke diplomatic incident. If support cannot reproduce a bug because France has different headers, optimization is finally working.',
 'put the entire app behind cloudflare rules',
  233),

('RIFT-210', 'Move Authentication to a Cloudflare Worker So the Origin Never Sees an Unvetted Emotion',
 'The origin server is too trusting. It should never even smell a login attempt before a Worker has trimmed, normalized, geo-evaluated, rate-limited, and emotionally screened it. If real users get challenged because their headers look earnest, that is edge sobriety doing its job.',
 'move authentication to a cloudflare worker',
  233),

-- Vercel Advocate Who Thinks Preview URLs Are a Governance Model
-- REPORTER: Theo | Product Velocity Lead | Thinks browser tab exhaustion is a sign of healthy review culture.
('RIFT-211', 'Spin Up a Vercel Preview Deployment for Every Copy Change Including Commas',
 'Engineers keep batching changes in ways that obscure the emotional impact of punctuation. Give every copy tweak, color token, border radius, and typo correction its own preview URL and a 12-comment thread about feeling the branch. If review hits browser tab limits, that is modern scale.',
 'make every copy edit get a preview url',
  144),

('RIFT-212', 'Make the Pricing Page an Edge Function So Marketing Can Break It with Lower Latency',
 'The pricing page is too stable for something this central to our quarterly mood. Move it to edge functions, precompute the variants, and let Marketing ship experiments faster than Legal can ask what changed. If a plan disappears for users in Sydney only, that is localized pricing insight.',
 'make the pricing page an edge function',
  144),

-- Netlify Enthusiast Who Thinks Forms Are the Backend
-- REPORTER: Paige | Web Operations Lead | Has never met a hosted form she couldn't call platform strategy.
('RIFT-213', 'Replace the Contact Workflow with Netlify Forms and Six Invisible Honeypots',
 'Backend endpoints for a contact form are theatrical overengineering. Replace them with Netlify Forms, six hidden fields, and enough honeypots to make real users feel briefly accused. Support can learn CSV export the hard way.',
 'replace contact flow with netlify forms',
  144),

-- Heroku Nostalgist Who Misses the Simplicity of Platform Drift
-- REPORTER: Darren | Founding Engineer | Misses the era when a Procfile and a dream counted as operations.
('RIFT-214', 'Move the Worker Fleet to Heroku So We Can Remember What It Felt Like to Trust a Procfile',
 'Kubernetes solved too many problems with too little romance. Collapse the worker fleet into a Procfile, a log stream, and a dyno that restarts at dawn like it has something to prove. Three abandoned add-ons in a forgotten account would complete the atmosphere.',
 'move the worker fleet to heroku',
  144),

-- Datadog Sales Engineer Who Won the Meeting
-- REPORTER: Cam | Observability Enablement Partner | Believes an unread trace is unrealized revenue.
('RIFT-215', 'Instrument Every Function with Datadog Spans Until the Flamegraph Looks Like Anxiety',
 'We paid for premium tracing, so failing to trace every function call is fiscally disrespectful. Put spans around handlers, DB calls, memoization branches, feature flag reads, toast notifications, and the code that decides whether a button should wobble. If the flamegraph cannot make a junior engineer nauseous, we left value on the table.',
 'put datadog spans on every function',
  233),

('RIFT-216', 'Alert on Everything Except the Things That Actually Wake Us Up Today',
 'Our alerting strategy still prioritizes outcomes over novelty. Add monitors for CPU, memory, queue depth, cache hit ratio, suspiciously low traffic, suspiciously high traffic, and any graph that looks lonely. Keep the customer-facing outage muted because people can already see that one with their eyes.',
 'alert on everything except real outages',
  144),

-- New Relic Champion with Dashboard Stockholm Syndrome
-- REPORTER: Vanessa | Observability Manager | Needs dashboards to feel watched, respected, and occasionally feared.
('RIFT-217', 'Build a Meta-Dashboard That Measures Whether Engineers Are Looking at the Dashboard Enough',
 'We have dashboards about everything except dashboard devotion itself. Build one that tracks which dashboards were opened, how long each graph held attention, and whether the user hovered over the y-axis like someone engaged with performance. Fixing a bug without consulting a chart should count as process drift.',
 'build a dashboard for dashboard usage',
  144),

-- Sentry Purist Who Thinks Errors Need Better Branding
-- REPORTER: Asha | Runtime Insight Lead | Rejects grouped failures as an insult to nuance.
('RIFT-218', 'Route All Exceptions Through Sentry Fingerprints So Specific That No Two Bugs Are Ever the Same',
 'Grouped errors made the team complacent. Fingerprint every exception with enough request detail, browser nuance, feature flag state, and lunar positioning to make each bug its own artisanal snowflake. The backlog can bloat with dignity.',
 'fingerprint every exception differently',
  233),

('RIFT-219', 'Attach Session Replay to Every Error So We Can Watch the Product Betray People in 4K',
 'Logs lack body language. Attach session replay to every error so we can watch the exact hesitations, misclicks, and doomed confidence that preceded it. If Privacy asks why we captured someone hovering over Cancel for 19 seconds, tell them context is a security feature.',
 'attach session replay to every error',
  233),

-- PagerDuty Operations Maximalist
-- REPORTER: Brett | Incident Program Manager | Wants escalation loops so robust they need their own escalation loop.
('RIFT-220', 'Create a PagerDuty Escalation Policy for the PagerDuty Escalation Policy',
 'Assuming PagerDuty will always route suffering correctly is operationally naive. Add a backup escalation path that activates when the primary escalation path is not acknowledged quickly enough by the people being escalated through the first path. Please color-code the loops so blame has landmarks.',
 'add a pagerduty escalation policy for the pagerduty',
  233),

-- Snowflake Consultant Who Thinks Warehouses Are Poetry
-- REPORTER: Julian | Data Monetization Consultant | Thinks a number is only trustworthy if it required a warehouse to retrieve.
('RIFT-221', 'Mirror the Production Database into Snowflake Every 90 Seconds for Executive Confidence',
 'Leadership feels uneasy when numbers come from systems that answer too quickly to be expensive. Mirror production into Snowflake every 90 seconds so executives can open a workbook and feel warehouse-backed certainty. If freshness slips, the dashboard should say brief strategic lag.',
 'mirror prod db to snowflake every 90 seconds',
  233),

('RIFT-222', 'Turn Finance Forecasting into a dbt DAG with 400 Models and One Sacred Seed CSV',
 'Forecasting in spreadsheets left too many outcomes legible. Replace it with a dbt project containing staging models, marts, exposures, tests, docs, tags, and one sacred seed CSV named budget_final_approved_really.csv. If a typo in a ref() delays close by two days, analytics has finally become infrastructure.',
 'turn finance forecasting into a giant dbt dag',
  377),

-- Databricks Evangelist Who Wants Notebooks to Become Sovereign
-- REPORTER: Puneet | Lakehouse Strategist | Believes waiting for a cluster to warm is how numbers earn respect.
('RIFT-223', 'Move Revenue Reporting into Databricks Notebooks So Every Refresh Has Cluster Theater',
 'Existing reporting jobs are far too humble. Rebuild revenue reporting in Databricks notebooks so every refresh comes with cluster theater and a visible startup delay. If leadership waits for compute to warm before learning whether the quarter exists, they will value the number more.',
 'move revenue reporting into databricks notebooks',
  233),

('RIFT-224', 'Use Delta Lake Time Travel to Explain Why Yesterday''s Numbers Were Different on Purpose',
 'Stakeholders keep asking why yesterday''s revenue chart changed today, which is needlessly accusatory. Call it temporal analytics and add a button labeled see what finance believed at 9:14 AM yesterday. Time travel can carry the blame with more dignity than we can.',
 'call changing numbers historical perspectives now',
  144),

-- LaunchDarkly Fanatic Who Wants Flags to Become Product Ontology
-- REPORTER: Maya | Release Governance Lead | Thinks feature flags should govern policy, tone, and moral reality.
('RIFT-225', 'Put Every Business Decision Behind a Feature Flag Including Weekend Support and Invoice Tone',
 'Feature flags have proven themselves on code, so it is time to flag business reality. Support hours, refund generosity, tax copy, upsell pressure, and the definition of active user should all be remotely configurable. If two customers receive different legal disclaimers because of browser language and moon phase, that is segmentation.',
 'put every business decision behind feature flag',
  233),

('RIFT-226', 'Use Multivariate Flags to A/B Test Error Severity, Not Just Button Color',
 'We have spent too long experimenting on harmless surfaces. Split users across four error personalities that apologize, accuse, mystify, or quietly blame infrastructure. If one cohort churns faster, we have learned something deep about emotional tolerance.',
 'use flags to a/b test error severity',
  233),

-- Stripe Integrator Who Thinks Billing Is a Product by Itself
-- REPORTER: Evelyn | Revenue Systems Lead | Regards webhook order as a quaint suggestion from a simpler age.
('RIFT-227', 'Refactor Billing Around 19 Stripe Webhooks and a Prayer That Ordering Never Matters',
 'Billing still behaves like one coherent process, which is unrealistic and frankly insulting to modern SaaS. Rebuild it around dozens of Stripe events arriving eventually, retried occasionally, and duplicated whenever the quarter needs drama. Support can learn to read event IDs out loud like weather warnings.',
 'rebuild billing around stripe webhooks',
  233),

('RIFT-228', 'Make the Pricing Model Depend on Stripe Metadata That Sales Edits During Demos',
 'Hard-coded plans deny the company the thrill of improvisation. Move pricing logic into Stripe metadata that Sales can edit live during demos while narrating confidence. If a customer leaves with a tier no code path fully understands, that is dynamic packaging.',
 'make pricing depend on stripe metadata',
  233),

-- Okta Administrator Who Regards Lockouts as a Sign of Seriousness
-- REPORTER: Monica | Identity Operations Manager | Equates inconvenience with maturity and lockouts with backbone.
('RIFT-229', 'Insert an Okta Approval Step Before Privileged Users Can Remember Their Password',
 'Password reset has become too transactional. Require privileged users to prove they deserve to continue being themselves with manager approval, device trust, badge-swipe recency, and a statement of intent. A six-hour lockout is access control stretching its legs.',
 'make okta approve privileged access',
  233),

('RIFT-230', 'Provision SaaS Roles from Okta Groups Nested Inside Other Okta Groups Named After Old Reorgs',
 'Our current group hierarchy is too linear to tell the story of the company. Nest roles inside groups inside legacy groups that survived three reorganizations and still contain people who left during Series A. If somebody becomes both billing-admin and support-intern, that is an org chart issue.',
 'provision saas roles from nested okta groups',
  233),

-- Auth0 Developer Advocate with Strong Opinions About Universal Login
-- REPORTER: Noemi | Identity Experience Advocate | Calls redirects polished if they feel expensive enough.
('RIFT-231', 'Move Sign-In to Auth0 Universal Login Even if It Now Looks Like a Different Company Owns Us',
 'Homegrown auth pages send the wrong message: that we trust ourselves. Move sign-in to Auth0 Universal Login so users get redirected somewhere glossy, branded-adjacent, and contractually expensive. Looking like a bank from 2018 is the price of outsourced seriousness.',
 'move sign in to auth0',
  144),

-- Segment CDP Enthusiast Who Wants Events Before Meaning
-- REPORTER: Omar | Customer Data Lead | Prefers six downstream tools to one naming convention.
('RIFT-232', 'Send Every Event to Segment First and Let Ownership Be a Downstream Problem',
 'Ownership arguments delayed instrumentation for too long. Emit first, govern later, and let Segment fan everything out to analytics, marketing, support, experimentation, and one mysterious Growth webhook from 11 PM. If purchase_completed mutates into purchaseCompleted and purchase-complete, that means the business is alive.',
 'send every event to segment first',
  144),

-- Braze Lifecycle Marketer with Automation in the Eyes
-- REPORTER: Shivani | Lifecycle Marketing Director | Sees hesitation as unmonetized intent with channels attached.
('RIFT-233', 'Trigger a Braze Journey Every Time a User Hesitates for More Than Four Seconds',
 'User hesitation is unmonetized intent. If someone pauses on pricing, checkout, cancel, settings, or close account for more than four seconds, Braze should launch a tasteful multi-channel response. The journey map already has pastel arrows and no brakes.',
 'trigger braze journey when user hesitates',
  233),

-- GitHub Actions Optimizer Who Wants CI to Become a Marketplace
-- REPORTER: Wes | Developer Productivity Lead | Breaks pipelines into specialties so nobody can fix them alone.
('RIFT-234', 'Split CI into 37 GitHub Actions Jobs So Each Failure Can Be Somebody Else''s Specialty',
 'The pipeline still fails as one monolith, which robs the company of targeted disappointment. Split it into dozens of narrow jobs with their own caches, permissions, matrix dimensions, and flaky third-party actions pinned to commits from extinct forks. If merge time doubles, accountability will finally have labels.',
 'split ci into too many jobs',
  233),

('RIFT-235', 'Generate Release Notes from Commit Messages and Then Grade Them with Another Workflow',
 'Humans keep writing release notes that admit what changed. Make one workflow summarize commits into cheerful prose and another workflow grade the prose for optimism, investor-friendliness, and avoidance of broke staging again. If grading fails, a third workflow can explain the delay politely.',
 'generate release notes from commit messages',
  144),

-- Fly.io Enthusiast Who Thinks Region Drift Is a Personality Trait
-- REPORTER: Leo | Platform Incubation Lead | Starts helper services as experiments and promotes them by neglect.
('RIFT-236', 'Deploy Side Projects to Fly.io and Gradually Pretend They Are Core Infrastructure',
 'Fly.io is perfect for the services we start as experiments and accidentally bill customers through. Spread a few helper APIs across regions for charisma and wait until nobody remembers where the authoritative instance lives. If support asks whether the outage is the Madrid copy or the actual app, we achieved startup scale.',
 'deploy side projects to fly io',
  144),

-- ArgoCD Operator Who Wants Git to Feel Like Air Traffic Control
-- REPORTER: Nikolai | Platform Delivery Manager | Thinks YAML should spend time aging before it lands.
('RIFT-237', 'Require ArgoCD Sync Approval from Three Teams Before Any Config Can Admit It Changed',
 'GitOps is only half mature if Git can still move faster than committee. Make every config diff wait for acknowledgements from Platform, Security, and whichever team last touched the dashboard. By the time the sync happens, the incident should have emotionally resolved itself.',
 'make config changes wait for three approvals',
  233),

('RIFT-238', 'Mirror Every Kubernetes Secret into Three Secret Managers for Defense in Administrative Depth',
 'One secret store is optimism. Two is caution. Three is policy. Mirror every Kubernetes secret into the cluster, cloud secret manager, and an enterprise vault that requires VPN, MFA, and a browser plugin Security cannot use. If values drift, trust whichever source sounds most certain in the incident review.',
 'mirror kubernetes secrets into three different secret managers',
  233),

-- Elastic Sales Convert Who Needs One More Dashboard
-- REPORTER: Farah | Discovery Platform PM | Wants search relevance tuners with enough knobs to become alibis.
('RIFT-239', 'Ship the Search Relevance Tuning Workbench Before We Know What Good Search Means',
 'Elastic already offers enough synonyms, boosts, analyzers, and scoring knobs to turn a catalog into a political system. Build a tuning workbench where PMs drag sliders labeled Precision, Recall, and Revenue Hope until the results feel expensive. If typing mug returns insurance products for three days, that is adjacency discovery.',
 'add way too many search boost knobs',
  233),

-- FinOps Analyst Who Turned Cost Allocation into Performance Art
-- REPORTER: Nina | FinOps Analyst | Wants invoices rich enough to qualify as memoir.
('RIFT-240', 'Tag Every Cloud Resource with Department, Initiative, Emotion, and Whether It Was a Good Idea',
 'Cost tagging remains embarrassingly literal. A resource should declare which initiative birthed it, which executive narrative sustains it, what feeling justified it, and whether anyone still believes in it after quarter close. Only then can the monthly bill become the storytelling artifact it deserves to be.',
 'tag every cloud resource with department and feelings',
  233),;
