-- HAVOC: launch ops, release trains, rollback panic, coordination blasts, and ship-day chaos
INSERT OR REPLACE INTO community_backlog (id, title, description, kickoff_prompt, technical_debt) VALUES
-- Release Operations Director Keira
-- REPORTER: Keira | Release Operations Director | Knows launch momentum can impersonate readiness right up until strangers touch the feature.
('HAVOC-961', 'Force Every Launch Checklist to Ask Whether We Are Mistaking Momentum for Readiness',
 'Ship pressure has a way of making the calendar feel like proof. Add a step that separates actual readiness from the emotional volume generated by dates, exec excitement, and several people saying we are close enough.',
 'make launch checklists doubt momentum',
  144),

('HAVOC-962', 'Install a Rollback Bot That Deletes the Word Unless the Right Person Types It',
 'Rollback is never just technical. It is pride, sunk effort, and one terrifying moment where everyone hopes someone more senior says the word first. Add a war-room bot that eats unauthorized rollback messages so production does not stay in the blast zone waiting for hierarchy to clear its throat.',
 'install rollback bot for unauthorized rollbacks',
  144),

-- Change Management PM Rafael
-- REPORTER: Rafael | Change Management PM | Has watched too many release trains absorb random hitchhiker features because nobody wanted to create one more date.
('HAVOC-963', 'Label the Features Riding This Release Train Only Because Nobody Wanted Another Train',
 'Bundles keep picking up extra work not because it belongs, but because scheduling later feels weak and paperwork-heavy. Give the opportunistic riders their own carriage before indecision starts shipping as cargo.',
 'label features freeloading on release trains',
  144),

('HAVOC-964', 'Mark Launch Risks That Were Rewritten as Confidence Instead of Fixed',
 'Go/no-go meetings have a bad habit of turning sharp unresolved problems into owners, mitigations, and soothing tone. Add a launch-review panel that marks the risks that got laundered into calm language instead of actually fixed.',
 'mark launch risks laundered into confidence',
  144),

-- Program Release Manager Naomi
-- REPORTER: Naomi | Program Release Manager | Knows code is often the least dangerous part of launch day once enough calendars, timezones, and adjacent teams get involved.
('HAVOC-965', 'Mark the Point Where Coordination Became More Dangerous Than the Code',
 'At a certain scale, the riskiest part of launch is no longer the software. It is sequencing, handoffs, support prep, legal wording, sales awareness, and one unlucky timezone. Mark when orchestration overtakes code as the main threat.',
 'mark when coordination beats code as risk',
  144),

('HAVOC-966', 'Make Freeze Windows Explain Whether They Prevent Failure or Just Comfort the Elders',
 'Release freezes have genuine value and also suspicious amounts of seasonal mythology attached to them. Add a note explaining whether a freeze protects real stability or simply reenacts a ritual everyone feels safer performing every year.',
 'make freeze windows admit they calm execs',
  89),

-- Site Launch Coordinator Imogen
-- REPORTER: Imogen | Site Launch Coordinator | Distrusts anyone typing All Good twice while the room smells like hot laptops and airborne denial.
('HAVOC-967', 'Put a Tiny Sweating Dot Next to Anyone Who Says "All Good" Too Calmly During Launch',
 'Launch rooms run partly on information and partly on performance. If someone posts All Good twice while their soul is clearly on fire, the UI should say so for them.',
 'add sweating dot to people saying all good',
  89),

('HAVOC-968', 'Split Release Notes into Customer Value and Things We Only Shipped to Unblock Ourselves',
 'Some release items help users. Others retire platform shame, remove internal pain, or unblock future work while getting dressed up as delight for symmetry. Separate the two before maintenance keeps winning marketing language it did not earn.',
 'split release notes into value and unblockers',
  144),

-- Dev Productivity Lead Ben
-- REPORTER: Ben | Dev Productivity Lead | Worries every emergency path eventually becomes the favorite path for people holding deadlines and active delusions.
('HAVOC-969', 'Make the Hotfix Path Feel Dangerous Again',
 'Hotfixes become irresistible when the normal path is too slow, too ceremonial, or too clogged with process acoustics. Rebalance the flow so emergency shipping stops becoming the preferred route for anyone carrying a promise and a worried face.',
 'make the hotfix path feel dangerous again',
  144),

('HAVOC-970', 'Split Deployment Approval into "I Trust This" and "The Calendar Won"',
 'Approvals currently blur genuine technical belief with surrender to the schedule. Add separate states so the audit trail can show whether we shipped because the team trusted the build or because standing still felt socially unaffordable.',
 'split deploy approvals into trust or calendar',
  89),

-- Customer Launch Readiness PM Julia
-- REPORTER: Julia | Customer Launch Readiness PM | Thinks every launch should predict which tiny behavior change will make competent users the most personally furious.
('HAVOC-971', 'Pin the Most Personally Irritating Change to the Top of Every Launch Checklist',
 'Launch prep spends too much time admiring features and not enough time naming the tiny change most likely to ruin a stable customer workflow. Put the most personally irritating change at the top of the checklist before support learns it live and emotionally.',
 'pin most irritating change to launch checklist',
  144),

('HAVOC-972', 'Show the Adjacent Teams That Are Still Secretly Not Ready Yet',
 'Core teams love to feel ready while docs, billing, legal, training, and analytics lag just far enough behind to create a halo of danger. Add an unready-perimeter panel naming the neighboring teams still running on vibes before coordination by osmosis gets mistaken for a plan.',
 'show adjacent teams that are not ready',
  144),

-- Chief Delivery Officer Marceline
-- REPORTER: Marceline | Chief Delivery Officer | Can tell when a phased rollout is prudence and when it is just fear cut into thinner slices for easier internal consumption.
('HAVOC-973', 'Label Rollouts as "Risk Reduction" or "Anxiety in Installments"',
 'Phased launch can reduce risk or simply spread the same fear across more days and more Slack messages. Add an explicit rollout label before suspense starts posing as discipline.',
 'label rollouts risk reduction or installment anxiety',
  144),

('HAVOC-974', 'Ask Whether This Bug Was Bad or Just Bad During Launch Week',
 'A lot of defects are survivable until they happen inside the sacred heat of a launch window, where timing adds audience, symbolism, and five extra opinions per minute. Test for launch-amplified pain before the bug gets all the credit.',
 'ask if launch week made this bug',
  89),

-- VP of Controlled Disaster Felicity
-- REPORTER: Felicity | VP of Controlled Disaster | Believes some launches deserve recognition not for elegance but for the number of executives, lawyers, and nervous refreshes they consumed and still survived.
('HAVOC-975', 'Award a Flaming Gold Star to Launches That Survived by Eating Half the Org',
 'Some successful launches go out cleanly. Others require pages, reversions, support confusion, legal side-eyes, and enough leadership refreshing to warm a village. Mark the expensive survivors accordingly.',
 'award launches that ate half the org',
  144),;
