// Added /ping and /reject to enable PvP sabotage interactions.
export const SLASH_COMMANDS = ["/backlog", "/clear", "/support", "/preworkout", "/buddy", "/store", "/synergize", "/compact", "/who", "/ping", "/reject", "/help", "/about", "/fast", "/voice", "/blame", "/brrrrrr", "/feedback", "/bug", "/key", "/upgrade", "/leaderboard", "/achievements", "/profile", "/ticket", "/take", "/accept", "/abandon", "/alias", "/model", "/user"];

export const SLASH_COMMAND_DESCRIPTIONS: Record<string, string> = {
  "/backlog": "View and manage your task backlog",
  "/clear": "Clear the terminal screen",
  "/support": "Get help from support",
  "/preworkout": "Boost your coding energy",
  "/buddy": "Manage your coding buddy",
  "/store": "Browse the rewards store",
  "/synergize": "Combine your efforts",
  "/compact": "Compact conversation history",
  "/who": "See who's online",
  "/ping": "Ping another player",
  "/reject": "Reject an incoming request",
  "/help": "Show available commands",
  "/about": "About this application",
  "/fast": "Toggle fast mode",
  "/voice": "Toggle voice input",
  "/blame": "Check who broke it",
  "/brrrrrr": "Go full speed ahead",
  "/feedback": "Send feedback",
  "/bug": "Report a bug",
  "/key": "Manage API keys",
  "/upgrade": "Upgrade your plan",
  "/leaderboard": "View the leaderboard",
  "/achievements": "View your achievements",
  "/profile": "View your profile",
  "/ticket": "Create a support ticket",
  "/take": "Claim a task",
  "/accept": "Accept an incoming request",
  "/abandon": "Abandon a task",
  "/alias": "Manage command aliases",
  "/model": "Switch AI model",
  "/user": "View user info",
};
