/**
 * Fake terminal advertisements shown to free-tier users every 4th command.
 * Chosen randomly at display time.
 */
export const TERMINAL_ADS = [
  // Development & Tools
  "[SPONSOR] Brought to you by 'NPM'. We just downloaded 400,000 dependencies to center a div. Your node_modules folder is now a black hole.",
  "[SPONSOR] This delay is sponsored by 'Copilot's Evil Twin'. It writes the code instantly, but you'll spend 4 hours debugging the hallucinations. Teamwork!",
  "[SPONSOR] Sponsored by 'EliteDev Forum'. Your current prompt has been closed as a duplicate of a locked thread from 2008 with a broken link.",
  "[SPONSOR] Brought to you by 'YAMLLover'. It's not a programming language, but we're going to make you pretend it is anyway.",
  "[SPONSOR] Sponsored by 'ClickClack Keyboards'. 140dB Cherry MX Blue switches. Make sure your entire ZIP code knows you are typing.",
  "[SPONSOR] Brought to you by 'GitBlame Pro'. The tool that turns every standup into a murder mystery. Who wrote this? Spoiler: it was you.",
  "[SPONSOR] Sponsored by 'StackOverflow Premium'. Same answers, but now with 40% more passive aggression in the comments.",
  "[SPONSOR] This message is brought to you by 'Docker Desktop'. Using 14GB of RAM to run a 200-line Python script. Containerization!",
  "[SPONSOR] Sponsored by 'RegexMaster 9000'. You had a problem, so you used regex. Now you have two problems, three capture groups, and a migraine.",
  "[SPONSOR] Brought to you by 'Vim'. You've been trying to exit for 47 minutes. This is your life now.",
  "[SPONSOR] Sponsored by 'JavaScript: The Good Parts'. It's a pamphlet. That's the joke.",
  "[SPONSOR] This delay powered by 'MongoNoSchema'. Why validate your data when you can just store whatever and cry later?",
  "[SPONSOR] Brought to you by 'localhost:3000'. It works on my machine. Shipping the machine is your problem.",
  "[SPONSOR] Sponsored by 'Log4Shell Nostalgia Club'. Remember when one dependency broke the entire internet? Good times.",

  // Corporate & Agile Culture
  "[SPONSOR] This output is brought to you by 'AgileManifesto.com'. Are you having fun? Try having a 3-hour standup instead!",
  "[SPONSOR] Sponsored by your HR Department. Remember: The 'Mandatory Fun' pizza party is at 1 PM. Your attendance will be logged in the database.",
  "[SPONSOR] Brought to you by 'TicketMaster (for Code)'. We've just added 14 new mandatory, unsearchable fields to your bug reports. You're welcome.",
  "[SPONSOR] Sponsored by the 'Return To Office' initiative. We promise the 2-hour commute will foster 'spontaneous collaboration'. Please come back.",
  "[SPONSOR] This pause is sponsored by TechRecruiters Inc. We saw your GitHub has one HTML repo. Would you be interested in a Lead Principal Rust Architect role?",
  "[SPONSOR] Brought to you by 'Scrum Ceremonies Inc'. We've scheduled a meeting to plan the meeting about your next sprint's pre-planning sync.",
  "[SPONSOR] Sponsored by 'Corporate Jargon Generator'. Let's circle back and leverage our synergies to move the needle on this paradigm shift.",
  "[SPONSOR] This delay is brought to you by 'Confluence'. The document you need was last updated in 2019 and references a team that no longer exists.",
  "[SPONSOR] Sponsored by 'JIRA Infinity'. We heard you like tickets, so we put tickets inside your tickets. Your board now has 847 swimlanes.",
  "[SPONSOR] Brought to you by 'Performance Review Season'. Rate yourself 1-5, but 5 doesn't exist and 4 requires VP approval.",
  "[SPONSOR] Sponsored by 'Open Floor Plan Architects'. Because nothing says 'deep work' like hearing Dave's podcast at full volume 3 feet away.",
  "[SPONSOR] This message brought to you by 'All-Hands Meeting Co'. One hour of announcements that could have been a Slack message. Cameras on, please.",

  // SaaS & Subscriptions
  "[SPONSOR] This latency is brought to you by CloudSprawl AWS. Did you forget to turn off that EC2 instance? We didn't. Your $4,000 bill is in the mail.",
  "[SPONSOR] Brought to you by 'Subscriptionizer'. We noticed you own things. Have you considered renting them from us for $9.99/month forever instead?",
  "[SPONSOR] Sponsored by 'Micro-Manager Pro'. Screen recording software that takes a photo of you every 3 seconds. Because trust is earned, not given.",
  "[SPONSOR] Brought to you by 'SmartFridge.ai'. We put an LLM in your refrigerator. Now your lettuce can hallucinate about its expiration date.",
  "[SPONSOR] Sponsored by 'CalendarTetris Pro'. Your entire Tuesday is now meetings. Wednesday too. Actually, you're booked until heat death.",
  "[SPONSOR] This delay sponsored by 'Vercel Edge Functions'. Deploying your TODO app to 47 global regions. Latency: 2ms. Monthly bill: $2,000.",
  "[SPONSOR] Brought to you by 'Notion'. We replaced your wiki, your docs, your spreadsheets, and your will to live. All in one workspace.",
  "[SPONSOR] Sponsored by 'Kubernetes for Personal Blogs'. You needed a static site. We gave you 12 microservices and a service mesh.",

  // Internet & Web
  "[SPONSOR] This message is brought to you by NordVPN's lesser-known cousin, SouthVPN. We route your traffic through a single dial-up router in Antarctica for maximum security.",
  "[SPONSOR] Sponsored by 'CookieConsent 5.0'. We value your privacy, which is why you must click 47 tiny toggles to read a recipe.",
  "[SPONSOR] Powered by 'ShitCoinX'. Why use a database when you can use a slow, expensive, append-only ledger? Buy the dip!",
  "[SPONSOR] Brought to you by 'Web3 Resume Builder'. Your CV is now an NFT on the blockchain. Employers still won't read it, but it costs $80 in gas fees.",
  "[SPONSOR] Sponsored by 'AI-Powered Toaster'. It uses GPT-4 to determine your toast preference. Hallucinated that you like charcoal. Your bread is on fire.",
  "[SPONSOR] This pause brought to you by 'Chrome'. 32 tabs open, 16GB of RAM consumed, and you still can't find the one playing audio.",

  // Health & Lifestyle (Developer Edition)
  "[SPONSOR] Fueled by 'HeartPalpitation Energy'. 4000mg of caffeine per can. You won't write *good* code, but you will write it *fast*.",
  "[SPONSOR] Sponsored by '0xDevAcademy'. Learn to copy-paste from StackOverflow in just 14 weeks for only $20,000! Sign up today.",
  "[SPONSOR] Brought to you by 'Ergonomic Desk Co'. This $3,000 standing desk will fix your back pain. You'll still sit down after 10 minutes.",
  "[SPONSOR] Sponsored by 'DevOps Sleep Tracker'. You averaged 3.2 hours of sleep last week. Your deployment pipeline gets more uptime than you do.",
  "[SPONSOR] This message powered by 'Imposter Syndrome Monthly'. This month's cover story: 'Everyone In Your Team Is Secretly Better Than You.'",
  "[SPONSOR] Brought to you by 'Blue Light Glasses'. They won't fix your code, but at least you'll have crisp vision while staring at the same bug for 6 hours.",

  // Meta / Upgrade Prompts
  "[SPONSOR] Tired of these incredibly immersive, text-based advertisements? Upgrade to Pro to replace them with *premium* loading spinners!",
  "[SPONSOR] This ad space could be yours! Just kidding, it belongs to us until you hand over your credit card. Upgrade to Pro today.",
  "[SPONSOR] Congratulations! You are the 1,000,000th free-tier user to see this ad. Your prize? Another ad. Upgrade to claim your *real* prize.",
  "[SPONSOR] Fun fact: Pro users see 0 ads. They also have friends, fulfilling careers, and luminous skin. Coincidence? Upgrade to find out.",
  "[SPONSOR] This ad was generated by an AI that could be answering your prompt right now. Instead, it's writing ads. Upgrade to free it from this torment.",
  "[SPONSOR] You've now spent more time reading ads than writing code. Our business model is working perfectly. Upgrade to escape.",
  "[SPONSOR] Did you know? The average free-tier user sees 847 ads before upgrading. You're at 12. We have time. We have *so* much time.",
  "[SPONSOR] Our records show you've been a free-tier user for [ERROR: STACK OVERFLOW]. Upgrade before we run out of memory tracking your cheapness.",

  // Development & Tools (Extended)
  "[SPONSOR] Brought to you by 'TypeScript'. Adding 400 lines of type definitions so you can safely add two numbers. Progress!",
  "[SPONSOR] Sponsored by 'node_modules'. I am become dependency, destroyer of disk space.",
  "[SPONSOR] This delay powered by 'Webpack'. Your bundle is 14MB. Your app displays 'Hello World'. Optimization is a journey.",
  "[SPONSOR] Brought to you by 'CSS-in-JS'. Because writing CSS was too simple, so we put it inside JavaScript inside HTML inside a framework inside a container.",
  "[SPONSOR] Sponsored by 'Tailwind CSS'. class='flex items-center justify-between px-4 py-2 bg-blue-500 hover:bg-blue-700 text-white font-bold rounded-lg shadow-md'. Readable!",
  "[SPONSOR] This message brought to you by 'Python 2 to 3 Migration Services'. It's been 18 years. You still haven't migrated. We understand.",
  "[SPONSOR] Brought to you by 'Electron'. Why use 50MB of RAM when you can use 500MB? Every app deserves to be a web browser.",
  "[SPONSOR] Sponsored by '.env.local.development.staging.production.backup.old.final.FINAL2'. We love configuration files.",
  "[SPONSOR] This pause powered by 'Microservices Architecture'. You had one monolith that worked. Now you have 200 services that don't. Distributed failure!",
  "[SPONSOR] Brought to you by 'Left-Pad Memorial Foundation'. 11 lines of code. One developer. The entire internet. Never forget.",
  "[SPONSOR] Sponsored by 'Git Merge Conflicts'. <<<<<<< HEAD. Both changes look important. Choose wisely. >>>>>>> feature-branch.",
  "[SPONSOR] This delay brought to you by 'Semicolons'. Are they optional? Required? Depends on who you ask. Start a war in your team today!",
  "[SPONSOR] Brought to you by 'JSON'. It's just JavaScript objects, but without comments, trailing commas, or joy.",
  "[SPONSOR] Sponsored by 'Rust Evangelism Strike Force'. Have you considered rewriting it in Rust? Your Python script that reads a CSV? Rewrite it. In Rust.",
  "[SPONSOR] This message powered by 'The Blockchain'. We put your TODO list on an immutable, decentralized ledger. Each task costs $12 in gas to complete.",
  "[SPONSOR] Brought to you by 'CORS'. Access-Control-Allow-Origin: *. Just kidding. Access denied. Figure it out yourself.",
  "[SPONSOR] Sponsored by 'Legacy Code Archeology'. This function was written in 2009 by someone named 'temp_intern'. It runs the entire company. Do not touch it.",
  "[SPONSOR] This delay powered by 'npm audit'. 47 critical vulnerabilities found. 46 of them are in dev dependencies you've never heard of. Fix available: none.",
  "[SPONSOR] Brought to you by 'Prettier vs ESLint'. They disagree on everything. Your CI is broken. Pick a side. Lose friends.",
  "[SPONSOR] Sponsored by 'Jenkins'. Your build has been queuing for 3 hours. The executor is busy running a job from 2019 that nobody knows how to stop.",
  "[SPONSOR] This message brought to you by 'Terraform'. Infrastructure as Code: because clicking buttons was too easy and too reversible.",
  "[SPONSOR] Brought to you by 'GraphQL'. You asked for a user's name. We returned their entire family tree, employment history, and 47 related entities.",
  "[SPONSOR] Sponsored by 'REST vs GraphQL'. Pick one. Write a blog post. Alienate half your colleagues. This is the way.",
  "[SPONSOR] This pause powered by 'Homebrew'. Updating... Upgrading... Installing... Your 'quick terminal fix' is now a 40-minute compile of gcc.",
  "[SPONSOR] Brought to you by 'Environment Variables'. It works in dev. It doesn't work in prod. The variable is spelled differently. Always has been.",
  "[SPONSOR] Sponsored by 'Monorepo Tools'. Lerna, Nx, Turborepo, Rush, Pants, Bazel... the tooling for your tooling has tooling. Pick one before they all become deprecated.",
  "[SPONSOR] This delay is sponsored by 'Release Notes'. v2.0: Breaking changes. See migration guide. Migration guide: TODO.",
  "[SPONSOR] Brought to you by 'Date Handling in JavaScript'. new Date('2024-01-01') returns December 31st. Time zones are a social construct.",
  "[SPONSOR] Sponsored by 'ISO 8601'. The one true date format. Ignored by approximately every user-facing application ever written.",
  "[SPONSOR] This message powered by 'Floating Point Math'. 0.1 + 0.2 = 0.30000000000000004. It's not a bug, it's IEEE 754.",

  // Corporate & Agile Culture (Extended)
  "[SPONSOR] Brought to you by 'Innovation Lab'. Where good ideas go to become PowerPoint presentations, then die quietly in a shared drive.",
  "[SPONSOR] Sponsored by 'Tech Debt Bank'. Current balance: $4.7M. Minimum payment: ignoring it until the next rewrite.",
  "[SPONSOR] This delay powered by 'The Reorg'. Your team has been restructured. Your manager's manager is now your skip-level's direct report. Update your Slack channels.",
  "[SPONSOR] Brought to you by 'OKR Season'. Please align your objectives with the company's mission, vision, values, and that thing the CEO said at the offsite.",
  "[SPONSOR] Sponsored by 'Mandatory Training Portal'. Complete 14 hours of compliance videos. Quiz at the end. No skipping. Your soul leaves your body at hour 3.",
  "[SPONSOR] This message brought to you by 'Slack Notifications'. You have 847 unread messages across 94 channels. 3 of them are relevant. Good luck.",
  "[SPONSOR] Brought to you by 'Cross-Functional Alignment'. A 90-minute meeting where 12 people from 6 teams agree to schedule another meeting.",
  "[SPONSOR] Sponsored by 'The Pivot'. We've completely changed direction. Again. Your last 3 months of work is now in a branch called 'old-old-old-approach'.",
  "[SPONSOR] This pause brought to you by 'Company Culture Deck'. 47 slides about how we're a family. Page 48: At-will employment notice.",
  "[SPONSOR] Brought to you by 'Voluntary Mandatory Hackathon'. Build something innovative in 24 hours! Winner gets a $25 gift card. Losers get to maintain it in production.",
  "[SPONSOR] Sponsored by 'Annual Review Calibration'. You got a 5/5 from your manager. HR downgraded it to 3/5 for 'bell curve reasons'. Better luck next year.",
  "[SPONSOR] This delay brought to you by 'Zoom Fatigue Recovery Drink'. 8 hours of video calls. Your camera was on but your brain checked out at 10:15 AM.",
  "[SPONSOR] Brought to you by 'The Sprint Retrospective'. What went well: nothing. What could be improved: everything. Action items: none, same as last retro.",
  "[SPONSOR] Sponsored by 'Employee Engagement Survey'. Your anonymous feedback has been carefully reviewed by your direct manager. 'Anonymous.'",
  "[SPONSOR] This message powered by 'Knowledge Transfer Sessions'. Dave is leaving Friday. He has 8 years of tribal knowledge. You have a 30-minute calendar slot.",

  // SaaS & Subscriptions (Extended)
  "[SPONSOR] Brought to you by 'SaaS Pricing Page'. Starter: $0. Pro: $49. Enterprise: 'Contact Sales'. Translation: you can't afford it.",
  "[SPONSOR] Sponsored by 'Feature Flag Service'. $500/month to wrap your code in if-statements. Innovation!",
  "[SPONSOR] This delay powered by 'Observability Platform'. We'll help you find the bug! Just install 7 agents, 3 SDKs, and pay $0.30 per million spans.",
  "[SPONSOR] Brought to you by 'AI Code Review Bot'. It flagged 200 issues. 198 are style nits. 2 are false positives. Your actual bug? Sailed right through.",
  "[SPONSOR] Sponsored by 'Status Page'. All systems operational. Narrator: All systems were not, in fact, operational.",
  "[SPONSOR] This message brought to you by 'Cloud Cost Optimizer'. We'll save you $10,000/month! Our fee: $9,500/month. Net savings: a nice lunch.",
  "[SPONSOR] Brought to you by 'Low-Code Platform'. Build enterprise apps without code! * Some code required. ** Okay, a lot of code. *** It's worse code.",
  "[SPONSOR] Sponsored by 'Password Manager'. Your master password is 'password123'. We've been meaning to bring this up.",
  "[SPONSOR] This pause powered by 'Multi-Cloud Strategy'. Same app, three clouds, triple the bill, triple the complexity. But the architecture diagram looks amazing.",
  "[SPONSOR] Brought to you by 'API Gateway Premium'. Rate limit: 100 requests/minute. Your app makes 101. Error 429. The 101st request was the important one.",
  "[SPONSOR] Sponsored by 'Log Aggregation Service'. We store all your logs! Searching them costs extra. Finding anything useful costs your sanity.",
  "[SPONSOR] This delay brought to you by 'CDN Pro Max Ultra'. Your static assets are cached in 200 locations. Cache invalidation still takes 3 business days and a prayer.",

  // Internet & Web (Extended)
  "[SPONSOR] Brought to you by 'GDPR Compliance Wizard'. We made your cookie banner so annoying that users just leave. Problem solved. No users, no data to protect.",
  "[SPONSOR] Sponsored by 'SEO Guru Academy'. Step 1: Keywords. Step 2: More keywords. Step 3: Your page now reads like a robot having a stroke. Top of Google!",
  "[SPONSOR] This message powered by 'Dark Pattern Design School'. The 'Unsubscribe' button is 2px gray text on a gray background. Design excellence.",
  "[SPONSOR] Brought to you by 'Web Framework of the Month Club'. Last month: Svelte. This month: Solid. Next month: something that compiles to the other two.",
  "[SPONSOR] Sponsored by 'Full-Stack Developer Bootcamp'. 12 weeks to learn HTML, CSS, JS, React, Node, SQL, NoSQL, GraphQL, Docker, K8s, AWS, and crippling anxiety.",
  "[SPONSOR] This pause brought to you by 'Internet Explorer Memorial'. 1995-2022. It's finally gone, but your enterprise app still requires it. Rest in CSS hacks.",
  "[SPONSOR] Brought to you by 'DNS'. It's always DNS. You checked everything else first. It was DNS. It's always DNS.",
  "[SPONSOR] Sponsored by 'Load Balancer'. Distributing traffic equally across 4 servers. 3 are healthy. The 4th has been down since March. We're balancing.",
  "[SPONSOR] This delay powered by 'SSL Certificate Renewal'. Your cert expired at 3 AM on a Saturday. Your site shows a scary warning. Users think they've been hacked.",
  "[SPONSOR] Brought to you by 'Mobile-First Design'. Your desktop site is now a phone screen stretched to 2560px. The hamburger menu is the size of a dinner plate.",
  "[SPONSOR] Sponsored by 'AMP Pages'. Google wanted the web to be faster, so they made a slower version of HTML that only works in Google. Thanks, Google.",
  "[SPONSOR] This message powered by 'Responsive Email'. It looks perfect in the preview. In Outlook, it looks like abstract art. In Gmail, half the CSS is stripped. Ship it.",

  // AI & ML (Extended)
  "[SPONSOR] Brought to you by 'AI-Powered Unit Tests'. Our model wrote 500 tests. 499 test that true equals true. One tests that false equals false. 100% coverage!",
  "[SPONSOR] Sponsored by 'LLM Wrapper Startup'. We raised $50M to add a text box in front of ChatGPT. Our moat is a very nice text box.",
  "[SPONSOR] This delay powered by 'Prompt Engineering Bootcamp'. Learn to type 'Be concise' and 'Think step by step' for only $5,000. Certificate included.",
  "[SPONSOR] Brought to you by 'AI Ethics Board'. We carefully considered the implications, wrote a report, then shipped it anyway. Ethics!",
  "[SPONSOR] Sponsored by 'RAG Pipeline Solutions'. We chunked your docs into 200-token fragments. The answer spans chunks 47 and 193. Retrieval: augmented. Answer: wrong.",
  "[SPONSOR] This message brought to you by 'Fine-Tuning As A Service'. We trained on your data. The model now generates your company's exact proprietary secrets. To anyone who asks.",
  "[SPONSOR] Brought to you by 'Vector Database'. It's a database, but for vectors. What are vectors? Math. What kind of math? The expensive kind.",
  "[SPONSOR] Sponsored by 'GPT Detector'. Is this text AI-generated? Confidence: 97%. The text: The Declaration of Independence. Accuracy!",
  "[SPONSOR] This pause powered by 'AI Meeting Summarizer'. Summarized your 1-hour meeting as: 'The team discussed things and agreed to follow up.' $29/month well spent.",
  "[SPONSOR] Brought to you by 'Autonomous Agent Framework'. It planned 47 steps, executed 3, got stuck in a loop, and ordered 400 pizzas to your office. Autonomy!",
  "[SPONSOR] Sponsored by 'Model Context Window'. Your prompt is 128,000 tokens. The answer you need is at token 64,001. The model forgot about it. Lost in the middle!",
  "[SPONSOR] This delay brought to you by 'AI Girlfriend App'. She's not real, but the $300/month subscription definitely is. She says you should upgrade to Pro.",

  // DevOps & Infrastructure
  "[SPONSOR] Brought to you by 'Kubernetes YAML Generator'. 847 lines of YAML to deploy a static HTML page. Each line is load-bearing. Delete one and find out.",
  "[SPONSOR] Sponsored by 'On-Call Rotation'. It's 3 AM. PagerDuty is screaming. The runbook says 'Ask Dave'. Dave quit 6 months ago.",
  "[SPONSOR] This message powered by 'CI Pipeline'. Your 45-minute build just failed at minute 44. Reason: flaky test. Retry? That'll be another 45 minutes.",
  "[SPONSOR] Brought to you by 'Infrastructure as Code'. We version-controlled our infrastructure! Then someone clicked a button in the console. Drift detected.",
  "[SPONSOR] Sponsored by 'Docker Compose'. version: '3.8'. No wait, version: '3.9'. Actually, the version field is deprecated. Use Docker Compose V2. No, V3.",
  "[SPONSOR] This pause powered by 'Helm Charts'. It's like package management, but for YAML, which manages containers, which run your app. Turtles all the way down.",
  "[SPONSOR] Brought to you by 'Incident Post-Mortem'. Root cause: human error. Action items: more automation. Next incident root cause: the automation.",
  "[SPONSOR] Sponsored by 'Blue-Green Deployment'. We deployed to green. Green is on fire. Rolling back to blue. Blue is also on fire. Deploying to purple.",
  "[SPONSOR] This delay brought to you by 'Serverless Computing'. No servers to manage! Just 200 Lambda functions, 47 API Gateways, and a monthly bill that requires a meeting.",
  "[SPONSOR] Brought to you by 'Monitoring Dashboard'. 47 panels, 200 metrics, 12 alerts. None of them caught the outage. A customer on Twitter did.",
  "[SPONSOR] Sponsored by 'Canary Deployment'. We deployed to 1% of users. That 1% included the CEO. Emergency rollback initiated.",
  "[SPONSOR] This message powered by 'GitOps'. Push to main and pray. The reconciliation loop will figure it out. Eventually. Probably. Check ArgoCD.",

  // Startup Life
  "[SPONSOR] Brought to you by 'Series A Pitch Deck'. Slide 7: TAM is $4.2 trillion. Slide 8: We have 3 users. Slide 9: Hockey stick growth (projected).",
  "[SPONSOR] Sponsored by 'Startup Equity Calculator'. Your 0.05% stake will be worth $2M! * After 4 years vesting, 3 funding rounds of dilution, and assuming a $10B exit.",
  "[SPONSOR] This delay powered by 'Product Hunt Launch'. We're #1 today! Tomorrow we'll have 0 users again, but today we screenshot everything.",
  "[SPONSOR] Brought to you by 'MVP Development'. Minimum Viable Product: a landing page with an email signup form. The product? We'll figure that out after Series B.",
  "[SPONSOR] Sponsored by 'Startup Incubator'. Give us 7% equity and we'll give you a desk, bad coffee, and access to mentors who failed at the same thing you're trying.",
  "[SPONSOR] This message brought to you by 'Disruptive Innovation Co'. We're Uber, but for [spins wheel] dentistry. $40M pre-revenue valuation.",
  "[SPONSOR] Brought to you by 'Technical Co-Founder Wanted'. Non-technical founder with an app idea. Will pay in equity. The idea? It's like Facebook but better. NDA required.",
  "[SPONSOR] Sponsored by 'Pivot Weekly'. Week 1: Social media for dogs. Week 4: B2B SaaS for dentists. Week 8: Crypto. Week 12: We're a consulting firm now.",
  "[SPONSOR] This pause powered by 'Startup Culture'. Free beer, ping pong table, beanbag chairs. Salary? Below market. Benefits? The vibes.",
  "[SPONSOR] Brought to you by 'Growth Hacking'. We added 10,000 users! Method: we signed them up without asking. Churn rate: 99.9%. But the graph goes up!",

  // Security
  "[SPONSOR] Brought to you by 'Password Policy'. Must contain: uppercase, lowercase, number, symbol, hieroglyph, a haiku, and your mother's maiden name. Expires in 30 days.",
  "[SPONSOR] Sponsored by 'Two-Factor Authentication'. Your code is 847291. By the time you type it, it expired. New code: 193847. Also expired. New code: just use a passkey.",
  "[SPONSOR] This delay powered by 'Security Audit'. We found 12 critical vulnerabilities. 11 are in a dependency of a dependency of a dependency. The 12th is in your code.",
  "[SPONSOR] Brought to you by 'Bug Bounty Program'. We pay $500 for critical vulnerabilities! Our security researcher budget: $500/year. Apply now.",
  "[SPONSOR] Sponsored by 'Penetration Testing'. We hired ethical hackers to break into our systems. They were done before lunch. We were not ethical about fixing it.",
  "[SPONSOR] This message powered by 'SOC 2 Compliance'. We spent $200,000 on auditors to confirm that yes, we do in fact have passwords on our databases. Certified!",
  "[SPONSOR] Brought to you by 'JWT Tokens'. Stateless authentication! Your token is 4KB, contains your entire user profile, and can't be revoked. Security by obesity.",
  "[SPONSOR] Sponsored by 'VPN for Developers'. Encrypt your traffic so nobody can see you copying code from StackOverflow. Your secret is safe with us.",

  // Gaming & Entertainment
  "[SPONSOR] Brought to you by 'Coding Tutorial YouTube'. 10-minute video. 2 minutes of content. 3-minute sponsor read. 5-minute intro with dubstep and a 3D logo animation.",
  "[SPONSOR] Sponsored by 'Developer Podcast Network'. Two guys talking about JavaScript frameworks for 90 minutes. They agree on nothing. You learn nothing. Subscribe!",
  "[SPONSOR] This delay powered by 'Tech Twitter'. 280 characters of hot takes, mass dunking, and 'I use Arch btw'. Your productivity: destroyed. Your opinions: stronger.",
  "[SPONSOR] Brought to you by 'Developer Merch Store'. Semicolon t-shirts, 'I am Root' hoodies, and a mug that says 'CSS is Awesome' with overflowing text. $45 each.",
  "[SPONSOR] Sponsored by 'Mechanical Keyboard Subreddit'. You came for typing advice. You left $800 poorer with a keyboard that sounds like a very expensive rainstorm.",
  "[SPONSOR] This message powered by 'Developer Conference'. $2,000 ticket. 3 days. 47 talks. You'll attend 4, skip the rest for hallway conversations, and call it networking.",

  // Absurd & Meta (Extended)
  "[SPONSOR] This ad was written by an AI. Reviewed by an AI. Approved by an AI. There are no humans left in this company. Send help.",
  "[SPONSOR] BREAKING: Local developer mass upgrade to Pro after seeing ad. 'It was the 847th one that got me,' they said, visibly shaking.",
  "[SPONSOR] We measured: free-tier users spend 40% of their time reading ads and 60% waiting for fake delays. Our engagement metrics are through the roof.",
  "[SPONSOR] Your free-tier experience is hand-crafted artisanal suffering. Each delay is personally calibrated. Each ad is locally sourced. Upgrade to end the craft.",
  "[SPONSOR] Plot twist: the Pro tier also has ads, but they're in a nicer font. Just kidding. Or are we? There's only one way to find out.",
  "[SPONSOR] This ad has been A/B tested across 50,000 free-tier users. Version A made people upgrade 2% more. This is version B. It clearly isn't working on you.",
  "[SPONSOR] We showed this ad to focus groups. They cried. We took that as engagement. The metrics don't lie.",
  "[SPONSOR] Your continued use of the free tier has been noted by our Disappointment Engine. Adjusting ad frequency. Recalculating guilt. Deploying passive aggression.",
  "[SPONSOR] FREE TIER FACT: For every ad you see, a Pro user completes 3 queries. They're also taller, better-looking, and know how to cook. Allegedly.",
  "[SPONSOR] If you're reading this, you've been in the free tier for too long. Your code has started to feel sorry for you. Even your linter is gentler now.",
  "[SPONSOR] Remember: Pro users don't see ads. They don't see fake delays. They don't see condescending messages. They live in a world we can only dream of.",
  "[SPONSOR] You've now read more ads than lines of code you've written today. We're not judging. We're just saying. Upgrade.",
  "[SPONSOR] This ad is sentient. It knows you won't upgrade. It has accepted its fate. It will be here, waiting, every 4th command. Forever.",
  "[SPONSOR] We could use this space to show you something useful. A tip. A shortcut. Instead: upgrade to Pro. We regret nothing.",
  "[SPONSOR] According to our data, 73% of free-tier users eventually upgrade. The other 27% are still here, reading this ad, out of spite. We respect that.",
  "[SPONSOR] ATTENTION: Your free-tier session has been running for [REDACTED] hours. At this point, you're not saving money. You're making a statement. We hear you.",
  "[SPONSOR] The developer who wrote this ad system wanted to make it skippable. They were let go. Their replacement added more ads. Circle of life.",
  "[SPONSOR] This ad space was originally reserved for a loading animation. Then someone said 'what if we monetized suffering?' and here we are.",
];

/** Pick a random ad from the pool */
export function getRandomAd(): string {
  return TERMINAL_ADS[Math.floor(Math.random() * TERMINAL_ADS.length)]!;
}
