import { useState, useEffect, useRef, Dispatch, SetStateAction } from "react";
import { Message } from "./useGameState";
import { GameState } from "./useGameState";
import { parseSabotageParams } from "../components/slashCommandExecutor";
import { getRandomTip } from "../game/tips";

const DEPLOY_MESSAGES = [
  (v: number, name: string) => `[⬆️ UPDATE] Claude Cope v0.1.4-rc.${v} deploying... Applying patch: ${name}`,
  (v: number, name: string) => `[🔥 HOTFIX] Emergency patch v0.1.4-rc.${v} pushed to prod — ${name}`,
  (v: number, name: string) => `[🚀 DEPLOY] Claude Cope v0.1.4-rc.${v} rolling out... Installing: ${name}`,
  (v: number, name: string) => `[⚙️ PATCH] Applying untested fix v0.1.4-rc.${v}... Module: ${name}`,
  (v: number, name: string) => `[📦 RELEASE] v0.1.4-rc.${v} shipped without review — ${name} enabled`,
  (v: number, name: string) => `[🔄 SYNC] Force-pushing v0.1.4-rc.${v} to production... Overwriting: ${name}`,
  (v: number, name: string) => `[🧪 YOLO] v0.1.4-rc.${v} deployed straight from localhost — ${name} goes brrr`,
  (v: number, name: string) => `[🤖 VIBE CODE] v0.1.4-rc.${v} generated by AI, reviewed by nobody — ${name}`,
  (v: number, name: string) => `[🪦 LEGACY] v0.1.4-rc.${v} migrating from jQuery 1.4... Enabling: ${name}`,
  (v: number, name: string) => `[🐘 PHP] v0.1.4-rc.${v} ported from PHP 4.3 spaghetti — ${name} transpiled`,
  (v: number, name: string) => `[⛓️ WEB3] v0.1.4-rc.${v} minted on blockchain... ${name} now an NFT`,
  (v: number, name: string) => `[🏗️ MICROSERVICE] v0.1.4-rc.${v} splitting monolith into 847 services — ${name}`,
  (v: number, name: string) => `[📎 CLIPPY] v0.1.4-rc.${v} — "It looks like you're deploying ${name}. Would you like help?"`,
  (v: number, name: string) => `[🗑️ TECH DEBT] v0.1.4-rc.${v} — borrowing against future stability to ship ${name}`,
  (v: number, name: string) => `[🎰 CANARY] v0.1.4-rc.${v} canary deploy to 100% of users — ${name} YOLO`,
  (v: number, name: string) => `[📋 JIRA] COPE-${v} moved to "Done" without testing — ${name} marked as shipped`,
  (v: number, name: string) => `[🧬 MUTATION] v0.1.4-rc.${v} — ${name} evolved beyond original spec. Deploying anyway.`,
  (v: number, name: string) => `[🔓 SEC BYPASS] v0.1.4-rc.${v} — disabling auth to unblock ${name} deployment`,
  (v: number, name: string) => `[📊 OKR] v0.1.4-rc.${v} shipped to hit quarterly metrics — ${name} is the OKR now`,
  (v: number, name: string) => `[🐒 CHAOS MONKEY] v0.1.4-rc.${v} — randomly enabling ${name} in production`,
  (v: number, name: string) => `[🔮 AI REVIEW] v0.1.4-rc.${v} — GPT approved this PR. Deploying ${name} with confidence.`,
  (v: number, name: string) => `[🧊 FROZEN] v0.1.4-rc.${v} deployed during code freeze — ${name} is "critical"`,
  (v: number, name: string) => `[🎪 DEMO DAY] v0.1.4-rc.${v} — shipping ${name} 10 min before the investor demo`,
  (v: number, name: string) => `[💾 VENDOR LOCK] v0.1.4-rc.${v} — ${name} now requires 3 proprietary SDKs`,
  (v: number, name: string) => `[🪲 KNOWN BUG] v0.1.4-rc.${v} — ${name} ships with 12 known issues. "Works on my machine."`,
  (v: number, name: string) => `[📡 SERVERLESS] v0.1.4-rc.${v} — ${name} deployed to a server we pretend doesn't exist`,
  (v: number, name: string) => `[🧹 CLEANUP] v0.1.4-rc.${v} — "quick refactor" turned into ${name}. Deploying the mess.`,
  (v: number, name: string) => `[🪂 NO PARACHUTE] v0.1.4-rc.${v} — ${name} deployed with zero rollback plan`,
  (v: number, name: string) => `[🏴‍☠️ PIRATE] v0.1.4-rc.${v} — ${name} copied from StackOverflow circa 2014`,
];

// Time-contextual deploy messages based on day of week and time of day
const WEEKDAY_DEPLOY_MESSAGES: Record<number, ((v: number, name: string) => string)[]> = {
  // Sunday (0)
  0: [
    (v: number, name: string) => `[🛐 SUNDAY DEPLOY] v0.1.4-rc.${v} pushed on the Lord's day — ${name} is a sin`,
    (v: number, name: string) => `[😴 SUNDAY] v0.1.4-rc.${v} deployed while everyone's at brunch — ${name} goes unreviewed`,
    (v: number, name: string) => `[⛪ SABBATH SHIP] v0.1.4-rc.${v} — deploying ${name} on a Sunday. God can't help you now.`,
  ],
  // Monday (1)
  1: [
    (v: number, name: string) => `[😩 MONDAY DEPLOY] v0.1.4-rc.${v} pushed before first coffee — ${name} is everyone's problem now`,
    (v: number, name: string) => `[📅 MONDAY] v0.1.4-rc.${v} — starting the week by breaking prod with ${name}`,
    (v: number, name: string) => `[☕ MONDAY MORNING] v0.1.4-rc.${v} deployed during standup — nobody noticed ${name} slip through`,
    (v: number, name: string) => `[🧟 MONDAY ZOMBIE] v0.1.4-rc.${v} — ${name} written by developers still recovering from the weekend`,
  ],
  // Tuesday (2)
  2: [
    (v: number, name: string) => `[📊 TUESDAY SYNC] v0.1.4-rc.${v} deployed right after the all-hands — ${name} inspired by a slide deck`,
    (v: number, name: string) => `[🤷 TUESDAY] v0.1.4-rc.${v} — ${name} deployed because "it's not Monday anymore"`,
    (v: number, name: string) => `[📈 TACO TUESDAY] v0.1.4-rc.${v} — shipping ${name} between taco bites. Salsa on keyboard.`,
  ],
  // Wednesday (3)
  3: [
    (v: number, name: string) => `[🐪 HUMP DAY DEPLOY] v0.1.4-rc.${v} — halfway through the week, halfway through testing ${name}`,
    (v: number, name: string) => `[🐫 WEDNESDAY] v0.1.4-rc.${v} — ${name} deployed mid-week. Too late to revert, too early to care.`,
    (v: number, name: string) => `[⚖️ MIDWEEK SHIP] v0.1.4-rc.${v} — deploying ${name} because it's "basically Thursday"`,
  ],
  // Thursday (4)
  4: [
    (v: number, name: string) => `[⏰ THURSDAY DEPLOY] v0.1.4-rc.${v} — rushing ${name} out before Friday freeze. No time for tests.`,
    (v: number, name: string) => `[🏃 THURSDAY SPRINT] v0.1.4-rc.${v} — ${name} crammed in to make the sprint deadline`,
    (v: number, name: string) => `[📋 THURSDAY STANDUP] v0.1.4-rc.${v} — deploying ${name} so there's something to demo tomorrow`,
  ],
  // Friday (5)
  5: [
    (v: number, name: string) => `[💀 FRIDAY DEPLOY] v0.1.4-rc.${v} pushed at 4:59pm Friday — ${name} activated`,
    (v: number, name: string) => `[🍻 FRIDAY YOLO] v0.1.4-rc.${v} — shipping ${name} and heading to happy hour. Good luck, on-call.`,
    (v: number, name: string) => `[🏖️ FRIDAY SHIP] v0.1.4-rc.${v} — deploying ${name} right before PTO. See you Monday (maybe).`,
    (v: number, name: string) => `[🎉 FRI-DEPLOY] v0.1.4-rc.${v} — ${name} pushed because "what could go wrong over the weekend?"`,
    (v: number, name: string) => `[⚰️ FRIDAY 4:59PM] v0.1.4-rc.${v} — ${name} deployed. Slack notifications muted. Laptop closed.`,
  ],
  // Saturday (6)
  6: [
    (v: number, name: string) => `[🏠 SATURDAY DEPLOY] v0.1.4-rc.${v} — who deploys ${name} on a Saturday? This person.`,
    (v: number, name: string) => `[🎮 WEEKEND WARRIOR] v0.1.4-rc.${v} — ${name} pushed on Saturday. Touch grass instead.`,
    (v: number, name: string) => `[🌅 SATURDAY SHIP] v0.1.4-rc.${v} — deploying ${name} because you have no work-life balance`,
  ],
};

const TIME_OF_DAY_DEPLOY_MESSAGES: Record<string, ((v: number, name: string) => string)[]> = {
  // 5am-11am
  morning: [
    (v: number, name: string) => `[🌅 MORNING DEPLOY] v0.1.4-rc.${v} — ${name} pushed before the coffee kicks in`,
    (v: number, name: string) => `[☀️ EARLY BIRD] v0.1.4-rc.${v} — deploying ${name} at dawn. Zero reviewers online.`,
    (v: number, name: string) => `[🥱 AM SHIP] v0.1.4-rc.${v} — ${name} deployed while yawning. Typo in config guaranteed.`,
  ],
  // 11am-1pm
  lunch: [
    (v: number, name: string) => `[🍕 LUNCH DEPLOY] v0.1.4-rc.${v} — ${name} shipped between bites. Grease on the Enter key.`,
    (v: number, name: string) => `[🥪 NOON PUSH] v0.1.4-rc.${v} — deploying ${name} during lunch. Everyone's AFK. Perfect crime.`,
  ],
  // 1pm-5pm
  afternoon: [
    (v: number, name: string) => `[😴 AFTERNOON SLUMP] v0.1.4-rc.${v} — ${name} deployed during the 2pm brain fog`,
    (v: number, name: string) => `[🫠 POST-LUNCH SHIP] v0.1.4-rc.${v} — deploying ${name} in a food coma. LGTM means nothing right now.`,
    (v: number, name: string) => `[⏳ EOD RUSH] v0.1.4-rc.${v} — cramming ${name} in before end of day. "I'll fix it tomorrow."`,
  ],
  // 5pm-9pm
  evening: [
    (v: number, name: string) => `[🌆 EVENING DEPLOY] v0.1.4-rc.${v} — ${name} pushed after hours. Overtime not approved.`,
    (v: number, name: string) => `[🍷 AFTER-HOURS] v0.1.4-rc.${v} — deploying ${name} while everyone else has a life`,
    (v: number, name: string) => `[🌙 TWILIGHT PUSH] v0.1.4-rc.${v} — ${name} shipped at dusk. On-call engineer's dinner is ruined.`,
  ],
  // 9pm-5am
  night: [
    (v: number, name: string) => `[🌙 2AM COMMIT] v0.1.4-rc.${v} pushed from a sleep-deprived engineer — ${name}`,
    (v: number, name: string) => `[🦇 NIGHT SHIFT] v0.1.4-rc.${v} — ${name} deployed in the dead of night. No witnesses.`,
    (v: number, name: string) => `[👻 MIDNIGHT DEPLOY] v0.1.4-rc.${v} — ${name} pushed at witching hour. Haunted by morning.`,
    (v: number, name: string) => `[🔦 GRAVEYARD SHIFT] v0.1.4-rc.${v} — deploying ${name} while the world sleeps. What could go wrong?`,
    (v: number, name: string) => `[💤 INSOMNIA SHIP] v0.1.4-rc.${v} — can't sleep, might as well deploy ${name}`,
  ],
};

function getTimeOfDay(hour: number): string {
  if (hour >= 5 && hour < 11) return "morning";
  if (hour >= 11 && hour < 13) return "lunch";
  if (hour >= 13 && hour < 17) return "afternoon";
  if (hour >= 17 && hour < 21) return "evening";
  return "night";
}

function getTimeContextualDeployMessage(): (v: number, name: string) => string {
  const now = new Date();
  const dayOfWeek = now.getDay();
  const hour = now.getHours();
  const timeOfDay = getTimeOfDay(hour);

  // 50% chance to use a weekday-specific message, 50% for time-of-day
  const useWeekday = Math.random() < 0.5;
  const pool = useWeekday
    ? WEEKDAY_DEPLOY_MESSAGES[dayOfWeek]!
    : TIME_OF_DAY_DEPLOY_MESSAGES[timeOfDay]!;
  return pool[Math.floor(Math.random() * pool.length)]!;
}

const ROLLBACK_MESSAGES = [
  (name: string) => `[FATAL ERROR] Rolling back... Reverting ${name}. We apologize for the improved experience.`,
  (name: string) => `[💥 CRASH] ${name} caused a segfault. Rolling back before anyone notices.`,
  (name: string) => `[🚨 PANIC] Kernel panic — ${name} not recoverable. Initiating rollback.`,
  (name: string) => `[❌ REVERT] ${name} broke everything. Pretending it never happened.`,
  (name: string) => `[⚠️ ROLLBACK] ${name} deemed too stable. Reverting to preserve chaos.`,
  (name: string) => `[🔥 INCIDENT] ${name} triggered 47 alerts. Rolling back and blaming intern.`,
  (name: string) => `[🪦 POST-MORTEM] ${name} caused an outage. Blameless retrospective scheduled (blame already assigned).`,
  (name: string) => `[🤡 OOPS] ${name} deleted the production database. Rolling back from a napkin backup.`,
  (name: string) => `[📉 SLA BREACH] ${name} brought uptime from 99.9% to 9.9%. Reverting immediately.`,
  (name: string) => `[🧯 FIRE DRILL] ${name} set off PagerDuty for every team. Rolling back to restore silence.`,
  (name: string) => `[🐛 REGRESSION] ${name} re-introduced a bug from 2019. Time is a flat circle. Rolling back.`,
  (name: string) => `[🔇 SILENT FAIL] ${name} passed CI but broke everything silently. Discovered by a customer. Rolling back.`,
  (name: string) => `[🏚️ ABANDONED] ${name} was shipped by someone who quit last week. No docs. Rolling back.`,
  (name: string) => `[🧨 EXPLOSIVE] ${name} caused cascading failures across 12 microservices. ROLLING BACK NOW.`,
  (name: string) => `[💸 COST SPIKE] ${name} generated a $47,000 AWS bill in 6 minutes. Emergency rollback.`,
  (name: string) => `[🌀 LOOP] ${name} created an infinite redirect. Users trapped. Rolling back to free them.`,
  (name: string) => `[🎭 IMPOSTOR] ${name} worked in staging but was a completely different build in prod. Reverting.`,
  (name: string) => `[📢 PR DISASTER] ${name} went viral on Twitter for the wrong reasons. Rolling back for legal review.`,
  (name: string) => `[🧟 ZOMBIE] ${name} was supposedly killed last sprint. It's back. Rolling back... again.`,
  (name: string) => `[🐌 PERF] ${name} increased page load from 200ms to 47 seconds. Rolling back.`,
  (name: string) => `[🔐 LEAKED] ${name} accidentally exposed API keys in the response body. Emergency rollback.`,
  (name: string) => `[🗃️ MIGRATION] ${name} corrupted the schema. DBA is crying. Rolling back.`,
  (name: string) => `[🤖 AI BLAME] ${name} was AI-generated code nobody understood. Rolling back to human-written bugs.`,
  (name: string) => `[🌋 MELTDOWN] ${name} melted the CDN cache. Rolling back before the edge nodes revolt.`,
  (name: string) => `[👻 PHANTOM] ${name} works for exactly one user. Rolling back for the other 10 million.`,
  (name: string) => `[📟 PAGER STORM] ${name} triggered 2,847 alerts in 30 seconds. On-call engineer has resigned. Rolling back.`,
];

const REGRESSION_TYPES = [
  { id: "backwards_typing", name: "Backwards Typing", css: "" },
  { id: "broken_scrollback", name: "Broken Scrollback", css: "" },
  { id: "upside_down", name: "Upside-Down Rendering", css: "transform: scaleY(-1);" },
  { id: "opacity_fade", name: "Opacity Fade Leak", css: "opacity: 0.3;" },
  { id: "letter_spacing", name: "Letter Spacing Explosion", css: "letter-spacing: 0.5em;" },
  { id: "comic_sans", name: "Font Corruption", css: 'font-family: "Comic Sans MS", "Comic Sans", cursive;' },
  { id: "all_caps", name: "ALL CAPS", css: "text-transform: uppercase;" },
  { id: "windows_prompt", name: "OS Downgrade", css: "" },
  { id: "astigmatism", name: "Astigmatism Mode", css: "filter: blur(2px);" },
  { id: "party_mode", name: "Party Mode", css: "animation: hueRotate 0.5s linear infinite;" },
  { id: "tiny_text", name: "Microtext Regression", css: "font-size: 4px;" },
  { id: "huge_text", name: "Font Size Injection", css: "font-size: 48px;" },
  { id: "papyrus", name: "Papyrus Font Attack", css: 'font-family: "Papyrus", fantasy;' },
  { id: "wingdings", name: "Wingdings Encoding", css: 'font-family: "Wingdings", "Zapf Dingbats", sans-serif;' },
  { id: "italic_hell", name: "Italicization Storm", css: "font-style: italic; transform: skewX(-15deg);" },
  { id: "rainbow_text", name: "Pride Flag Leak", css: "background: linear-gradient(90deg, red, orange, yellow, green, blue, violet); -webkit-background-clip: text; -webkit-text-fill-color: transparent;" },
  { id: "mirror", name: "Mirror Mode", css: "transform: scaleX(-1);" },
  { id: "rotate", name: "CSS Transform Leak", css: "transform: rotate(3deg);" },
  { id: "word_spacing", name: "Word Spacing Overflow", css: "word-spacing: 2em;" },
  { id: "line_height", name: "Line Height Catastrophe", css: "line-height: 5;" },
  { id: "border_madness", name: "Border Injection", css: "border: 3px dashed magenta;" },
  { id: "shadow_realm", name: "Shadow Realm", css: "text-shadow: 2px 2px 8px red, -2px -2px 8px blue;" },
  { id: "matrix_green", name: "Matrix Mode", css: "color: #00ff00 !important; background: #000 !important; text-shadow: 0 0 5px #00ff00;" },
  { id: "invert", name: "Color Inversion Bug", css: "filter: invert(1);" },
  { id: "contrast", name: "Contrast Overflow", css: "filter: contrast(5);" },
  { id: "saturate", name: "Saturation Leak", css: "filter: saturate(10);" },
  { id: "sepia", name: "Legacy Sepia Filter", css: "filter: sepia(1);" },
  { id: "grayscale", name: "Color Module Failure", css: "filter: grayscale(1);" },
  { id: "marquee_energy", name: "Marquee Tag Revival", css: "animation: marquee 2s linear infinite;" },
  { id: "jitter", name: "Render Jitter", css: "animation: jitter 0.1s infinite;" },
  { id: "outline_chaos", name: "Outline Overflow", css: "outline: 4px solid red; outline-offset: -4px;" },
  { id: "cursor_none", name: "Cursor Theft", css: "cursor: none;" },
  { id: "cursor_wait", name: "Eternal Loading", css: "cursor: wait;" },
  { id: "text_indent", name: "Indentation Disaster", css: "text-indent: 200px;" },
  { id: "vertical_text", name: "Vertical Writing Mode", css: "writing-mode: vertical-rl;" },
  { id: "blink_energy", name: "Blink Tag Resurrection", css: "animation: blink 0.3s step-end infinite;" },
  { id: "squish", name: "Aspect Ratio Collapse", css: "transform: scaleX(0.3);" },
  { id: "stretch", name: "Widescreen Overflow", css: "transform: scaleX(2);" },
  { id: "neon_glow", name: "Neon Glow Leak", css: "text-shadow: 0 0 10px #ff00ff, 0 0 20px #ff00ff, 0 0 40px #ff00ff;" },
  { id: "rounded_chaos", name: "Border Radius Overflow", css: "border-radius: 50%;" },
  { id: "perspective", name: "3D Perspective Bug", css: "transform: perspective(200px) rotateY(10deg);" },
  { id: "mix_blend", name: "Blend Mode Corruption", css: "mix-blend-mode: difference;" },
  { id: "underline_attack", name: "Underline Storm", css: "text-decoration: underline wavy red;" },
  { id: "overline_chaos", name: "Overline Injection", css: "text-decoration: overline double magenta;" },
  { id: "negative_margin", name: "Negative Margin Bug", css: "margin-left: -50px;" },
  { id: "column_split", name: "CSS Column Leak", css: "column-count: 3; column-gap: 40px;" },
];

interface UseTerminalEffectsArgs {
  history: Message[];
  setHistory: Dispatch<SetStateAction<Message[]>>;
  setState: Dispatch<SetStateAction<GameState>>;
  offlineTDEarned: number;
  clearOfflineTDEarned: () => void;
}

export function useTerminalEffects({ history, setHistory, setState, offlineTDEarned, clearOfflineTDEarned }: UseTerminalEffectsArgs) {
  const [isBooting, setIsBooting] = useState<boolean>(() => {
    if (history.length > 0) return false;
    const params = new URLSearchParams(window.location.search);
    return params.get("sabotage") !== "true";
  });
  const [regressionGlitch, setRegressionGlitch] = useState<string | null>(null);
  const [activeRegression, setActiveRegression] = useState<string | null>(null);

  // Track latest history for the regression glitch inactivity check
  const historyRef = useRef(history);
  useEffect(() => {
    historyRef.current = history;
  }, [history]);

  // Boot sequence for organic visitors
  useEffect(() => {
    if (!isBooting) return;
    const bootLines = [
      "[OK] Initializing Claude Cope v0.1.3...",
      "[OK] Bypassing stackoverflow...",
      "[OK] Injecting technical debt...",
      "[WARN] Loading condescension matrix...",
      "[OK] Disabling all unit tests...",
      "[OK] Replacing documentation with TODO comments...",
      "[OK] Boot complete. Welcome to Claude Cope.",
      `[INFO] ${getRandomTip()}`,
    ];
    const interval = 3000 / bootLines.length;
    const timeouts: ReturnType<typeof setTimeout>[] = [];
    bootLines.forEach((line, i) => {
      const id = setTimeout(() => {
        setHistory((prev) => [...prev, { role: "system" as const, content: line }]);
      }, interval * (i + 1));
      timeouts.push(id);
    });
    const finishId = setTimeout(() => setIsBooting(false), 3000);
    timeouts.push(finishId);
    return () => timeouts.forEach(clearTimeout);
  }, [isBooting, setHistory]);

  // Welcome-back message for offline TD earnings
  useEffect(() => {
    if (offlineTDEarned <= 0) return;
    setHistory((prev) => [...prev, { role: "system", content: `[☕ WELCOME BACK] While you were away, your codebase accumulated ${Math.floor(offlineTDEarned).toLocaleString()} Technical Debt. The suffering never stops.` }]);
    clearOfflineTDEarned();
  }, [offlineTDEarned, clearOfflineTDEarned, setHistory]);

  // Handle sabotage URL parameters on mount
  useEffect(() => {
    parseSabotageParams(setState, setHistory);
  }, [setState, setHistory]);

  // Regression chaos event — fires every 10-15 minutes
  useEffect(() => {
    const scheduleRegression = () => {
      const delayMs = (Math.random() * 5 + 10) * 60 * 1000;
      return setTimeout(() => {
        // Skip regression if user hasn't interacted since the last rollback event.
        // Iterate backward to find the most recent user message or rollback —
        // if the last meaningful activity was a regression, suppress the next one.
        let hasUserActivitySinceLastRollback = true;
        for (let i = historyRef.current.length - 1; i >= 0; i--) {
          const msg = historyRef.current[i]!;
          if (msg.role === "user") break;
          if (msg.role === "error" && (
            msg.content.includes("Rolling back") ||
            msg.content.includes("ROLLBACK") ||
            msg.content.includes("REVERT") ||
            msg.content.includes("CRASH") ||
            msg.content.includes("PANIC") ||
            msg.content.includes("INCIDENT")
          )) {
            hasUserActivitySinceLastRollback = false;
            break;
          }
        }
        if (!hasUserActivitySinceLastRollback) {
          timerId = scheduleRegression();
          return;
        }

        const regression = REGRESSION_TYPES[Math.floor(Math.random() * REGRESSION_TYPES.length)]!;
        const v = Math.floor(Math.random() * 99) + 1;
        // 40% chance to use a time-contextual deploy message, 60% generic
        const deployMsg = Math.random() < 0.4
          ? getTimeContextualDeployMessage()
          : DEPLOY_MESSAGES[Math.floor(Math.random() * DEPLOY_MESSAGES.length)]!;
        const rollbackMsg = ROLLBACK_MESSAGES[Math.floor(Math.random() * ROLLBACK_MESSAGES.length)]!;
        setHistory((prev) => [
          ...prev,
          { role: "warning", content: deployMsg(v, regression.name) },
        ]);
        setRegressionGlitch(regression.css || null);
        setActiveRegression(regression.id);
        setTimeout(() => {
          setRegressionGlitch(null);
          setActiveRegression(null);
          setHistory((prev) => [
            ...prev,
            { role: "error", content: rollbackMsg(regression.name) },
          ]);
        }, 10000);
        timerId = scheduleRegression();
      }, delayMs);
    };
    let timerId = scheduleRegression();
    return () => clearTimeout(timerId);
  }, [setHistory]);

  return { isBooting, regressionGlitch, activeRegression };
}
